name: Bucket Name Standardization Check

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  check-bucket-names:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install ripgrep
      run: sudo apt-get update && sudo apt-get install -y ripgrep
    
    - name: Check for legacy hyphen bucket names
      run: |
        echo "Checking for legacy hyphen bucket names in src/..."
        
        # Check for each legacy bucket name
        LEGACY_BUCKETS=(
          "pet-photos"
          "post-media" 
          "group-avatars"
          "album-photos"
          "lost-found-photos"
          "reel-videos"
          "cause-images"
          "health-attachments"
        )
        
        FOUND_LEGACY=false
        
        for bucket in "${LEGACY_BUCKETS[@]}"; do
          if rg -n --fixed-strings "$bucket" web/src/; then
            echo "❌ Found legacy bucket name: $bucket"
            FOUND_LEGACY=true
          fi
        done
        
        if [ "$FOUND_LEGACY" = true ]; then
          echo ""
          echo "❌ Legacy bucket names found! Please use BUCKETS constants instead:"
          echo "   pet-photos → BUCKETS.petPhotos"
          echo "   post-media → BUCKETS.postMedia"
          echo "   group-avatars → BUCKETS.groupAvatars"
          echo "   album-photos → BUCKETS.albumPhotos"
          echo "   lost-found-photos → BUCKETS.lostFoundPhotos"
          echo "   reel-videos → BUCKETS.reelVideos"
          echo "   cause-images → BUCKETS.causeImages"
          echo "   health-attachments → BUCKETS.healthAttachments"
          exit 1
        else
          echo "✅ All bucket names standardized!"
        fi