name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps (no audit/fund noise)
        run: npm install --no-audit --no-fund

      - name: Show repo tree (debug)
        run: |
          pwd
          ls -la
          echo "--- api ---"
          ls -la api || true
          echo "--- scripts ---"
          ls -la scripts || true

      - name: Verify features
        run: npm run -s verify:features

      - name: Typecheck
        run: npm run -s typecheck || true

      - name: Build
        run: npm run -s build
